server:
  port: 8101
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot?useSSL=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zach1989
  application:
    name: dubbo-consumer
mybatis:
  mapper-locations: classpath:mapper/*.xml
  map-underscore-to-camel-case: true
  default-fetch-size: 100
  default-statement-timeout: 30
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
dubbo:
  application:
    id: dubbo-consumer
    name: dubbo-consumer
  protocol:
    id: dubbo
    name: dubbo
    port: 12345